### ISSUE TITLE
Zusätzlicher Unterricht und Teilnahme an AGs

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild-NRW-GS-Zeugnisse#11]
Zur Diskussion
In der Sek 1 werden immer die Angaben "Zusätzliche Unterrichtsveranstaltung" und "AGs" mit auf dem Zeugnis gedruckt. Bei den GS Zeugnissen nur dann, wenn dort auch Kurse belegt sind. Wie sollte es sein?

**So ist es aktuell in den GS-Zeugnissen**:

![2022-11-17_133948](https://user-images.githubusercontent.com/79116896/202485149-70112ed4-890b-4e1f-9e61-16029c146529.png)

**So ist es in den Sek1 Zeugnissen:**

![2022-11-17_134044](https://user-images.githubusercontent.com/79116896/202485189-017e59fd-9a4c-4257-96c0-30a0e64d10f7.png)

**Comment by ATouloum** [comment]
Wie haben die AGs und den herkunftssprachlichen Unterricht einfach in das Feld "Zeugnisbemerkungen" geschrieben. Dazu haben wir Floskeln angelegt.

**Comment by st-bach** [comment]
Hallo Anne, in der Grundschule gibt es nicht so viele AG´s wie in der SI. Darum ist es denke ich ausreichend, wenn sie nur bei Teilnahme auf dem Zeugnis stehen.
