### ISSUE TITLE
Wiederbeginn des Unterrichts im Halbjahreszeugnis

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild-NRW-GS-Zeugnisse#14]
Liebe GS-Zeugnis-Experten,

mich würde eure Meinung zu folgender Unstimmigkeit, die im Forum aufgekommen ist, interessieren:

Aktuell wird beim Generieren des Halbjahreszeugnissen nach dem Wiederbeginn des Unterrichts gefragt, was im Zeugnis anschließend so abgebildet wird (den Default Wert werde ich mal auf today setzen):
![2023-01-12_153751](https://user-images.githubusercontent.com/79116896/212095293-cf18987e-7bdf-4e48-a1d5-b7d52ad5ccf2.png)

Laut Bass muss im Halbjahreszeugnis der Wiederbeginn des Unterrichts nicht mit drauf. 
Wie sehen Eure Zeugnisse aus. Habt ihr dazu Angaben gemacht? 

Über eine kurz Rückmeldung würde ich mich freuen.

**Comment by TorstenEngelke** [comment]
Hallo Anne,

bei den von mir betreuten Schulen wird der Wiederbeginn des Unterrichts angegeben, der Termin für die Elternsprechtage bzw. die Elternsprechtage nicht (ich kenne kaum Schulen, die da etwas angeben). 
Ich habe dem Kollegen, der im Forum danach fragte, die Abfrage aus dem Zeugnisreport gelöscht. Ich finde aber, dass der Wiederbeginn auch im Halbjahr ruhig auf dem Zeugnis stehen kann, da ich auch einige Schulen kenne, die am Montag nach den Zeugnissen einen Schilf-Tag machen und somit der Unterricht erst am Dienstag wieder beginnt.

LG, Torsten

**Comment by st-bach** [comment]
Hallo Anne,
ich habe den Wiederbeginn des Unterrichts auch auf unseren Zeugnissen stehen lassen, da einige Schulen Montag , … frei haben. Den Elternsprechtag habe ich rausgenommen.

LG Stefanie

**Comment by Krockhaus** [comment]
Guten Morgen Anne, guten Morgen Torsten,

ich sehe das genauso. Der Wiederbeginn kann ruhig auf das Zeugnis.

Liebe Grüße
Christian

**Comment by AnneSchueller** [comment]
Hallo zusammen,

vielen Dank für Eure Rückmeldungen. Somit lasse ich den Wiederbeginn auf den Halbjahreszeugnissen. 
Sollten in Zukunft mehrere Schulen danach fragen, wie man das rausnimmt, würde ich das ggf. als Option in der Ini-Datei festlegen.
