### ISSUE TITLE
Ini-Datei anpassen

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild-NRW-GS-Zeugnisse#16]
z.B. Option Fehlzeit = Versäumnistage kann entfernt werden

**Comment by st-bach** [comment]
Hallo Anne, folgende Punkte sind mir in der Ankreuzzeugnis Ini aufgefallen:
- die Option Fehlzeit = Versäumnistage kann tatsächlich entfernt werden.
- KlassenleitungText = Klassenleiterei    Text=Klassenleitung besser?
- ;FächerAufNeuerSeite 
- ;ASVSeite2
- FachKopfSichtbarE1=SG;LE;RS;SU;M;ER;KR;MU;MU;SP... also alle Fächer. Vielleicht ist das für die Kollegen einfacher. 
- die Kopfhöhe müsste etwas höher sein z.B. 25

Liebe Grüße
