### ISSUE TITLE
Vorschlag Optionen AnkreuzzeugnisEinstellungen.ini

### ISSUE THREAD

**Issue by st-bach** [SVWS-NRW/Schild-NRW-GS-Zeugnisse#22]
[Optionen]
;Linien
;Duplex=Vertikal
;MitJahrgang
Blocksatz
SchriftgroesseBemerkungen=10
NotenAbJahrgang=03
;Zusammmenhalten
Folgejahrgang
Vorname
KopfHoehe=25
FachPosition=Mitte
;FächerAufNeuerSeite
;FachKopfSichtbarE1=D;SU;ER;KU;MU;SG;M;SP;LE;RS;KR
;FachKopfSichtbarE2=SG;M;SP
;FachKopfSichtbar03=KR;RS;MU
;FachKopfSichtbar04=D;E;M
Unterschrift=VN
Ankreuzsymbol=X
Zeilenhoehe=5
;SchulleitungText=Schulleitung/Vertretung
PositionSchulleitungText=R
ASVText=Arbeitsverhalten
;ASVSeite2
LELSText=
BemerkungText=Bemerkung
;BemerkungLeerText=-keine-
;ZusammenhaltenE1=Englisch
;DeutschNotenEinzeln
SonderpaedagogeText=Fachberater Sonderpädagigik
;KlassenleitungText=Die Klassenleitung
;FoerderschwerpunktTextIndividuell
;WiderspruchInEingangsphaseAusblenden
NachnameInVersetzungsvermerk
;ASVAusblenden
BemerkungenAufNeuerSeite=E1;E2;E3;03;04
Fehlzeitentext=Versäumnistage
SchulbesuchsjahrText=Schuleingangsphase $JAHR$. Schulbesuchsjahr 
AbstandFaecher=5

**Comment by AnneSchueller** [comment]
Danke für die Hinweise, 
Ich habe alles soweit eingepflegt und mit Kommentaren ergänzt.
