### ISSUE TITLE
Grafik-Fehler beim GS-Zeugnisdruck (Ankreuzzeugnisse)

### ISSUE THREAD

**Issue by TorstenEngelke** [SVWS-NRW/Schild-NRW-GS-Zeugnisse#34]
Wenn ich ein GS-Zeugnis drucken möchte, dann kommt es zu einer Fehlermeldung (Grafikfehler) - derselbe Report funktioniert unter 2.0!
Wenn ich nun beim Dyn. Subreport des "GS-Kopfes" den Haken bei "visible" entferne, dann wird das Zeugnis (ohne Zeugniskopf) angezeigt. Muss man evtl. ein anderes Grafik-Format wählen?

Die SEKI-Zeugnisse funktionieren ja ohne Probleme.

![Grafikfehler](https://github.com/user-attachments/assets/e525d7da-2b50-4611-ae20-100c74fecc46)

**Comment by AnneSchueller** [comment]
Hallo Torsten,

wenn man den Zeugniskopf öffnet und die Grafik auswählt, muss folgende Option deaktiviert werden:
![image](https://github.com/user-attachments/assets/5d34943f-17e1-4b1e-926c-6f71a9600d96)

Wenn ich das in Schild2 geändert habe, musste ich den Kopf immer nochmal in Schild3 im Bearbeitungsmodus öffnen und die Grafik einmal anklicken...

Die Zeugnisse habe ich bereits im Git angepasst. Wir werden sie aber auch nochmal auf der Homepage aktualisieren.

**Comment by TorstenEngelke** [comment]
Jawoll, das war es, vielen Dank, Anne!

**Comment by TorstenEngelke** [comment]
Vielen Dank, Anne, das wusste ich nicht, mit deinem Tipp klappt alles wie gewünscht, lG

> -----Original Message-----
> From: "AnneSchueller" ***@***.***>
> Sent: 22.11.2024 10:14
> To: "SVWS-NRW/Schild-NRW-GS-Zeugnisse" ***@***.***>
> Cc: "TorstenEngelke" ***@***.***>
>  "Author" ***@***.***>
> Subject: Re: [SVWS-NRW/Schild-NRW-GS-Zeugnisse] Grafik-Fehler beim GS-Zeugnisdruck (Ankreuzzeugnisse) (Issue #34)
> 
> 
> Hallo Torsten,
> 
> wenn man den Zeugniskopf öffnet und die Grafik auswählt, muss folgende Option deaktiviert werden:
> ![image](https://github.com/user-attachments/assets/5d34943f-17e1-4b1e-926c-6f71a9600d96)
> 
> Wenn ich das in Schild2 geändert habe, musste ich den Kopf immer nochmal in Schild3 im Bearbeitungsmodus öffnen und die Grafik einmal anklicken...
> 
> Die Zeugnisse habe ich bereits im Git angepasst. Wir werden sie aber auch nochmal auf der Homepage aktualisieren. 
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/SVWS-NRW/Schild-NRW-GS-Zeugnisse/issues/34#issuecomment-2493281212
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

-- 
Mit freundlichen Grüßen,
Torsten Engelke

0152/28572080
