### ISSUE TITLE
Überschrift im Zeugnis über den Fächern bei Klasse 4 falsch

### ISSUE THREAD

**Issue by ATouloum** [SVWS-NRW/Schild-NRW-GS-Zeugnisse#9]
Bei Klasse 4 (bzw. Klasse 3 wenn nur Noten gegeben werden und keine Texte zu den Fächern) steht als Überschrift "Lernstand und Leistungsentwicklung". Das ist unpassend. Besser wäre wenn hier nur "Noten in den Fächern" stehen würde.

Ändern kann man das  indem man bei
procedure ZeugniseinstellungenLaden;

lblLernbereiche.Caption := LELSText
ändern in
lblLernbereiche.Caption := 'Noten in den Fächern';

**Comment by AnneSchueller** [comment]
Hallo Alex, beziehst du dich auf die aktuellen Textzeugnisse von der Homepage? Dort steht über dem Notenblock "Lernbereiche/Fächer"? 
Oder meinst du ein anderes Zeugnis?

**Comment by ATouloum** [comment]
Ich meine die Textzeugnisse von der HP(GSHybridZeugnis.rtm). Wenn du für die 4 Klasse dir die Vorschau zum Zeugnisdruck anschaust, dann steht da "Lernstand und Leistungsentwicklung". Kann es sein, dass du den Text über den Notenblock im Editor meinst?

**Comment by AnneSchueller** [comment]
Bei meiner DB sieht das Textzeugnis von der HP so aus:

![2022-12-17_192832](https://user-images.githubusercontent.com/79116896/208256309-5fc3064c-98b5-43f5-9c8a-a6e0cc815a15.png)

Gemeint ist doch der Text über dem Notenblock?

**Comment by ATouloum** [comment]
![Zeugnis](https://user-images.githubusercontent.com/116005051/208301655-20c8b600-6835-4715-9bc5-370c116031e2.png)

Bei mir sieht es so aus. (Konnte leider keine bessere Ansicht des Zeugnis` nehmen) Aber ich habe gerade die aktuelle Zeugnisvorlage runtergeladen und da ist es so wie bei dir... Entweder wurde was verändert bei der aktuellen Vorlage oder ich habe es im Prozess des Anpassens verändert und wusste es schlicht nicht mehr...

Davon abgesehen finde ich den Text "Noten in den Fächern" besser als "Lernbereiche / Fächer" ;) Aber das ist wohl Geschmackssache.

**Comment by AnneSchueller** [comment]
Die Zeugnisse auf der HP wurden im Oktober 22 aktualisiert. Es kann sein, dass der alte Download noch eine andere Überschrift hatte.
